using UnityEngine;

/// <summary>
/// The active chapter's skin: one switchable Resources folder (e.g. "Skins/Classic") that
/// every skinnable visual resolves through - block pieces, ground, the height-limit laser.
/// Chapter wiring sets <see cref="Folder"/> once at level load and every visual
/// follows. Sprites are generated by the Tools/ scripts; import settings are applied
/// automatically (see BlockSkinImportSettings); naming conventions live in ART.md.
///
/// Deliberately a code-owned static, NOT a serialized field: Unity bakes serialized
/// defaults into its import caches, where they go stale when values change in code
/// (see the folder-rename incident documented in PHYSICS.md's sister docs).
/// </summary>
public static class ChapterSkins
{
    /// <summary>Resources folder of the active chapter's skin.</summary>
    public static string Folder = "Skins/Classic";

    /// <summary>
    /// The chapter <see cref="Apply"/> latched, or null. THE run-scoped chapter snapshot:
    /// visuals that need chapter identity beyond sprites (the wave laser's accent colours)
    /// read this rather than re-deriving the chapter from menu-selection state, so art and
    /// colour can never come from different chapters.
    /// </summary>
    public static ChapterDefinition ActiveChapter { get; private set; }

    /// <summary>
    /// Point the skin at the given chapter (null = Classic). Must run before the first
    /// skinned visual loads (GameManager.Awake does, before the floor is configured).
    /// </summary>
    public static void Apply(ChapterDefinition chapter)
    {
        ActiveChapter = chapter;
        Folder = chapter != null ? chapter.SkinFolder : FallbackFolder;
    }

    private const string FallbackFolder = "Skins/Classic";

    /// <summary>Whole-piece sprite for a tetromino shape ("T" -> piece_T), or null.</summary>
    public static Sprite LoadPiece(string shape)
    {
        return string.IsNullOrEmpty(shape) ? null : LoadWithFallback($"piece_{shape}");
    }

    /// <summary>
    /// The plateau strip the blocks stand on, tiled to any floor width (no distortion).
    /// The only ground visual - chapter scenery lives in the backdrop, never on the floor.
    /// </summary>
    public static Sprite LoadPlateau() => LoadWithFallback("plateau");

    /// <summary>Optional chapter art for the height-limit laser line, or null.</summary>
    public static Sprite LoadLaser() => LoadWithFallback("laser");

    /// <summary>Seamless 1x1-unit masonry tile the grounded floor columns are built from.</summary>
    public static Sprite LoadGroundFill() => LoadWithFallback("ground_fill");

    /// <summary>Walkable cap band (2 x 0.5 units, horizontally seamless) laid along floor tops.</summary>
    public static Sprite LoadGroundCap() => LoadWithFallback("ground_cap");

    /// <summary>
    /// Chapters using baked carved ground relief. Keep this opt-in aligned with
    /// generate_ground_sprite.py; it selects cosmetic atmosphere, cut bevels and upright
    /// island art only. Classic and unknown folders keep the legacy fallback presentation.
    /// </summary>
    public static bool GroundHasCarvedRelief => Folder is
        "Skins/Jungle" or "Skins/Japan" or "Skins/Neon" or "Skins/Winter" or
        "Skins/Kvartal" or "Skins/Desert" or "Skins/Island" or "Skins/Fangkuai" or
        "Skins/LostCity" or "Skins/Volcano" or "Skins/Egypt" or "Skins/Tide" or
        "Skins/Techno" or "Skins/Hallow" or "Skins/Crimson";

    /// <summary>
    /// One floating support-island cell (1x1; variant 1..3 per chapter,
    /// see generate_ground_sprite.py). Out-of-range variants clamp to 1.
    /// </summary>
    public static Sprite LoadIsland(int variant)
    {
        if (variant < 1 || variant > IslandVariantCount) variant = 1;
        return LoadWithFallback($"island_{variant}");
    }

    /// <summary>Island looks per chapter (legacy art also gets x4 rotations at spawn).</summary>
    public const int IslandVariantCount = 3;

    // Partial skins are legal (ART.md: "only supply what should differ"): a chapter folder
    // overrides file-by-file and everything else falls back to the Classic skin.
    private static Sprite LoadWithFallback(string fileName)
    {
        Sprite sprite = string.IsNullOrEmpty(Folder)
            ? null
            : Resources.Load<Sprite>($"{Folder}/{fileName}");
        if (sprite == null && Folder != FallbackFolder)
        {
            sprite = Resources.Load<Sprite>($"{FallbackFolder}/{fileName}");
        }
        return sprite;
    }

    /// <summary>
    /// Shape token from any block identifier: "Block_T(Clone)", "Block_T" and "T" all
    /// yield "T". Used for prefab names and BlockDefinition display names alike.
    /// </summary>
    public static string ExtractShapeToken(string rawName)
    {
        if (string.IsNullOrWhiteSpace(rawName)) return null;

        string token = rawName;
        int parenIndex = token.IndexOf('(');
        if (parenIndex >= 0) token = token.Substring(0, parenIndex);
        token = token.Trim();

        int underscoreIndex = token.LastIndexOf('_');
        return underscoreIndex >= 0 && underscoreIndex < token.Length - 1
            ? token.Substring(underscoreIndex + 1)
            : token;
    }
}
