using UnityEngine;

/// <summary>
/// Tier-0 landing feedback (JUICE.md): EVERY landing gets physical feedback - layered impact
/// sound, dust at the contact edge, a skin squash, camera trauma and a haptic tick - all
/// scaled by how hard the piece came in. This is deliberately quality-blind: coins, chimes
/// and celebrations start at Tier 1 (the PlacementJudge, Phase 2); this layer only ever says
/// "something with mass just landed".
/// </summary>
public static class LandingFx
{
    // Layered impact: transient (precision click) + body (mass thud) + tail (dust settle).
    // Generated by Tools/generate_elevenlabs_sfx.py; until those clips exist the body layer
    // falls back to the old impact_heavy pair so landings are never silent again.
    private const int BodyVariants = 3;
    private const int TransientVariants = 3;
    private const int TailVariants = 2;

    /// <summary>Play the full Tier-0 stack. hardnessRaw01 = 0 softest steered descent .. 1 flick.</summary>
    public static void Play(BlockController block, float hardnessRaw01)
    {
        if (block == null) return;

        // Perceptual shaping: a held fast-drop (raw ≈ 0.37) should already feel meaty,
        // not like 37% of a flick.
        float hardness = Mathf.Pow(Mathf.Clamp01(hardnessRaw01), 0.65f);

        PlaySound(hardness);
        TowerCameraController.AddTrauma(0.15f + 0.4f * hardness);
        LandingSquashFx.Play(block, hardness);
        if (block.TryGetWorldBounds(out Bounds bounds)) LandingDustFx.Spawn(bounds, hardness);

        if (hardness < 0.35f) Haptics.Light();
        else if (hardness < 0.75f) Haptics.Medium();
        else Haptics.Heavy();
    }

    private static void PlaySound(float hardness)
    {
        // Body: the mass of the thud. Volume rides hardness; pitch drops a touch as it
        // hits harder (bigger = lower reads as heavier).
        float bodyPitch = Mathf.Lerp(1.04f, 0.94f, hardness);
        if (SfxPlayer.HasClip("land_body_01"))
        {
            SfxPlayer.PlayVariant("land_body", BodyVariants,
                Mathf.Lerp(0.3f, 0.95f, hardness), 0.06f, bodyPitch);
        }
        else
        {
            SfxPlayer.PlayVariant("impact_heavy", 2,
                Mathf.Lerp(0.25f, 0.7f, hardness), 0.07f, bodyPitch);
        }

        // Transient: the crisp contact click that sells precision. Optional layer.
        if (SfxPlayer.HasClip("land_transient_01"))
        {
            SfxPlayer.PlayVariant("land_transient", TransientVariants,
                Mathf.Lerp(0.18f, 0.5f, hardness), 0.08f);
        }

        // Tail: dust settling after a GENTLE placement. Hard slams skip it - their energy
        // should end on the thud, not a whisper.
        if (hardness < 0.55f && SfxPlayer.HasClip("land_tail_01"))
        {
            SfxPlayer.PlayVariant("land_tail", TailVariants, 0.22f, 0.1f);
        }
    }
}
