using UnityEngine;

/// <summary>
/// The active theme's skin: one switchable Resources folder (e.g. "Skins/Classic") that
/// every skinnable visual resolves through - block pieces, ground, the height-limit laser.
/// Future theme wiring sets <see cref="Folder"/> once at level load and every visual
/// follows. Sprites are generated by the Tools/ scripts; import settings are applied
/// automatically (see BlockSkinImportSettings); naming conventions live in ART.md.
///
/// Deliberately a code-owned static, NOT a serialized field: Unity bakes serialized
/// defaults into its import caches, where they go stale when values change in code
/// (see the folder-rename incident documented in PHYSICS.md's sister docs).
/// </summary>
public static class ThemeSkins
{
    /// <summary>Resources folder of the active theme's skin.</summary>
    public static string Folder = "Skins/Classic";

    /// <summary>
    /// Point the skin at the given theme (null = Classic). Must run before the first
    /// skinned visual loads (GameManager.Awake does, before the floor is configured).
    /// </summary>
    public static void Apply(ThemeDefinition theme)
    {
        Folder = theme != null ? theme.SkinFolder : FallbackFolder;
    }

    private const string FallbackFolder = "Skins/Classic";

    /// <summary>Whole-piece sprite for a tetromino shape ("T" -> piece_T), or null.</summary>
    public static Sprite LoadPiece(string shape)
    {
        return string.IsNullOrEmpty(shape) ? null : LoadWithFallback($"piece_{shape}");
    }

    /// <summary>
    /// The plateau strip the blocks stand on, tiled to any floor width (no distortion).
    /// The only ground visual - theme scenery lives in the backdrop, never on the floor.
    /// </summary>
    public static Sprite LoadPlateau() => LoadWithFallback("plateau");

    /// <summary>Optional themed art for the height-limit laser line, or null.</summary>
    public static Sprite LoadLaser() => LoadWithFallback("laser");

    // Partial skins are legal (ART.md: "only supply what should differ"): a theme folder
    // overrides file-by-file and everything else falls back to the Classic skin.
    private static Sprite LoadWithFallback(string fileName)
    {
        Sprite sprite = string.IsNullOrEmpty(Folder)
            ? null
            : Resources.Load<Sprite>($"{Folder}/{fileName}");
        if (sprite == null && Folder != FallbackFolder)
        {
            sprite = Resources.Load<Sprite>($"{FallbackFolder}/{fileName}");
        }
        return sprite;
    }

    /// <summary>
    /// Shape token from any block identifier: "Block_T(Clone)", "Block_T" and "T" all
    /// yield "T". Used for prefab names and BlockDefinition display names alike.
    /// </summary>
    public static string ExtractShapeToken(string rawName)
    {
        if (string.IsNullOrWhiteSpace(rawName)) return null;

        string token = rawName;
        int parenIndex = token.IndexOf('(');
        if (parenIndex >= 0) token = token.Substring(0, parenIndex);
        token = token.Trim();

        int underscoreIndex = token.LastIndexOf('_');
        return underscoreIndex >= 0 && underscoreIndex < token.Length - 1
            ? token.Substring(underscoreIndex + 1)
            : token;
    }
}
