using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Editor-only difficulty report for puzzle (Height-Limit Waves) levels. Wave heights are
/// SOLVED, not authored, and deterministic per level - so the whole difficulty curve can be
/// inspected as a table instead of replayed. Runs the same <see cref="WaveSolver"/> the live
/// mode runs, over every ClearWaves/Endless level carrying a HeightLimitWavesModifier, and
/// writes PuzzleWaveReport.md at the repo root.
///
/// Use it to bracket difficulty: playtest ONE or TWO levels to calibrate
/// WaveSolver.CantileverColumnsPerStep (how many columns of supported width a row of rise
/// buys) and the rank density table, then read the table to confirm the other levels instead
/// of playing all sixteen. Read the "outward" column: cumulative block cells as a fraction of
/// what fits WITHIN the floor footprint at that line. Below 1.0 the wave can be solved without
/// ever building past the floor edges; above 1.0 the player is forced to cantilever outward,
/// and how far above 1.0 says how much of the wave lives out there. ("fill" is close to
/// tautological - the line is solved to hit the density - so it only reveals waves where the
/// one-cell minimum rise, not the math, set the height.)
/// </summary>
public static class PuzzleWaveReport
{
    private const string LevelsFolder = "Assets/Resources/Levels";
    private const string OutputPath = "PuzzleWaveReport.md";
    private const int ExtraWavesBeyondGoal = 3; // endless continues past the win - show the tail

    [MenuItem("Tools/MadTowers/Puzzle Wave Report")]
    public static void Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Puzzle Wave Report");
        sb.AppendLine();
        sb.AppendLine("Generated by `Tools/MadTowers/Puzzle Wave Report` (editor-only). Solved by the");
        sb.AppendLine("same `WaveSolver` the live mode uses, so these ARE the heights a run will see.");
        sb.AppendLine();
        sb.AppendLine("Difficulty is two screws, both set by the asset's `difficultyRank`: the required");
        sb.AppendLine("packing **density**, and the **flank slope** the solver believes the player can hold");
        sb.AppendLine($"(`{WaveSolver.CantileverColumnsPerStep}` column of supported width per N rows of rise, per side):");
        sb.AppendLine();
        sb.AppendLine("| rank | density | flank slope |");
        sb.AppendLine("|---:|---|---|");
        for (int rank = 1; rank <= 5; rank++)
        {
            sb.AppendLine($"| {rank} | {WaveSolver.DensityForWave(rank, 1):F2} → " +
                          $"{WaveSolver.DensityForWave(rank, 100):F2} | " +
                          $"1 col / {WaveSolver.CantileverRowsPerStepFor(rank)} rows |");
        }
        sb.AppendLine();
        sb.AppendLine("`line` = the SOLVED capacity height (what the difficulty math means, and what");
        sb.AppendLine("`fill`/`outward` are computed against). `laser` = where the beam is actually drawn");
        sb.AppendLine("and zaps: the nearest row boundary plus half a cell of wobble clearance");
        sb.AppendLine("(`WaveSolver.LaserCellsForSolvedHeight`), so it always reads `x.5` and the rows that");
        sb.AppendLine("fit under it are exactly the rows that fit under `line`.");
        sb.AppendLine();
        sb.AppendLine("`fill` = block cells / buildable cells under the solved line (≈ the density by");
        sb.AppendLine("construction; a value BELOW it means the one-cell minimum rise set that line).");
        sb.AppendLine("`outward` = block cells / cells available inside the floor footprint only. Below 1.0 the");
        sb.AppendLine("wave fits over the floor; above 1.0 the player is forced to cantilever outward.");
        sb.AppendLine("`flank/side` = the same thing in absolute cells: cells that must hang past the floor edge,");
        sb.AppendLine("split over the two sides, given the whole rows that fit under the laser. This is the number");
        sb.AppendLine("that predicts playability - rank 5 asked 36 cells/side at wave 5 on the chapter-1 floor (a");
        sb.AppendLine("sustained 3-column overhang), which playtested as impossible; rank 3 asks 14. On a stepped or");
        sb.AppendLine("gapped floor read it as an AVERAGE - the flanks are not interchangeable, and the low side");
        sb.AppendLine("carries more than half.");
        sb.AppendLine();

        string[] guids = AssetDatabase.FindAssets("t:LevelDefinition", new[] { LevelsFolder });
        var rows = new List<(string level, int rank, int wavesToWin, string floor, float avgCells, string table, float goalOutward, float goalFlank, float goalLine, bool hasWin)>();

        var columnTops = new List<float>();
        var footprintTops = new List<float>();   // no cantilever: what fits over the floor alone
        var heights = new List<float>();

        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            LevelDefinition level = AssetDatabase.LoadAssetAtPath<LevelDefinition>(path);
            if (level == null) continue;

            HeightLimitWavesModifier waves = FindWaveModifier(level);
            if (waves == null) continue;

            GameModeConfig config = level.GameModeConfig;
            IReadOnlyList<FloorSegmentConfig> segments = config != null ? config.FloorSegments : null;
            WaveSolver.BuildColumnTops(segments, columnTops, waves.DifficultyRank);
            WaveSolver.BuildColumnTops(segments, footprintTops, waves.DifficultyRank,
                includeCantilever: false);
            float avgCells = WaveSolver.AverageCellsPerPiece(
                config != null ? config.BlockBag : null, WaveSolver.MagmaRate(config));

            // Endless-paired wave levels have no win wave; show the same depth but never
            // label one, or the table invents a goal the level does not have.
            bool hasWin = level.TargetType == LevelTargetType.ClearWaves;
            int wavesToWin = hasWin ? Mathf.Max(1, Mathf.RoundToInt(level.TargetValue)) : 5;
            int shown = wavesToWin + ExtraWavesBeyondGoal;
            WaveSolver.SolveLineHeights(columnTops, avgCells, waves.DifficultyRank, shown, heights);

            var table = new StringBuilder();
            table.AppendLine("| wave | quota | cumulative | density | line (cells) | laser | rise | capacity | fill | outward | flank/side |");
            table.AppendLine("|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|---:|");
            float goalOutward = 0f;
            float goalFlank = 0f;
            for (int n = 1; n <= shown; n++)
            {
                int cumulative = WaveSolver.CumulativeQuota(n);
                float line = heights[n - 1];
                float rise = n > 1 ? line - heights[n - 2] : line;
                float capacity = WaveSolver.CapacityAt(columnTops, line);
                float blockCells = cumulative * avgCells;
                float fill = capacity > 0f ? blockCells / capacity : 0f;
                float footprint = WaveSolver.CapacityAt(footprintTops, line);
                float outward = footprint > 0f ? blockCells / footprint : 0f;
                // Whole rows only, and measured under the LASER (where the player actually builds
                // to), so this is the real "how much must hang past the floor" bill per side.
                float usableRows = Mathf.Floor(WaveSolver.LaserCellsForSolvedHeight(line));
                float flankPerSide = Mathf.Max(0f,
                    blockCells - WaveSolver.CapacityAt(footprintTops, usableRows)) * 0.5f;
                if (n == wavesToWin) { goalOutward = outward; goalFlank = flankPerSide; }
                string marker = !hasWin ? " *(endless)*"
                    : n == wavesToWin ? " **(win)**" : (n > wavesToWin ? " *(endless)*" : "");
                table.AppendLine($"| {n}{marker} | {WaveSolver.QuotaForWave(n)} | {cumulative} | " +
                    $"{WaveSolver.DensityForWave(waves.DifficultyRank, n):F3} | {line:F1} | " +
                    $"{WaveSolver.LaserCellsForSolvedHeight(line):F1} | {rise:F1} | " +
                    $"{capacity:F0} | {fill:F2} | {outward:F2} | {flankPerSide:F0} |");
            }

            rows.Add((level.name, waves.DifficultyRank, wavesToWin, DescribeFloor(segments), avgCells,
                table.ToString(), goalOutward, goalFlank, heights[wavesToWin - 1], hasWin));
        }

        rows.Sort((a, b) => string.Compare(a.level, b.level, System.StringComparison.Ordinal));

        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("| level | rank | waves to win | line at the win wave | outward | flank/side | floor |");
        sb.AppendLine("|---|---:|---:|---:|---:|---:|---|");
        foreach (var row in rows)
        {
            sb.AppendLine($"| {row.level} | {row.rank} | {(row.hasWin ? row.wavesToWin.ToString() : "endless")} | {row.goalLine:F1} | {row.goalOutward:F2} | {row.goalFlank:F0} | {row.floor} |");
        }
        sb.AppendLine();

        foreach (var row in rows)
        {
            sb.AppendLine($"## {row.level}");
            sb.AppendLine();
            sb.AppendLine($"rank {row.rank} (density {WaveSolver.DensityForWave(row.rank, 1):F2}→" +
                          $"{WaveSolver.DensityForWave(row.rank, 100):F2}, flank 1 col / " +
                          $"{WaveSolver.CantileverRowsPerStepFor(row.rank)} rows) · " +
                          $"{(row.hasWin ? row.wavesToWin + " waves to win" : "endless (no win wave)")} · avg cells per counted block {row.avgCells:F2} · floor {row.floor}");
            sb.AppendLine();
            sb.Append(row.table);
            sb.AppendLine();
        }

        File.WriteAllText(OutputPath, sb.ToString());
        Debug.Log($"[PuzzleWaveReport] {rows.Count} puzzle level(s) written to {Path.GetFullPath(OutputPath)}");
    }

    private static HeightLimitWavesModifier FindWaveModifier(LevelDefinition level)
    {
        IReadOnlyList<LevelModifier> modifiers = level.Modifiers;
        if (modifiers == null) return null;
        for (int i = 0; i < modifiers.Count; i++)
        {
            if (modifiers[i] is HeightLimitWavesModifier waves) return waves;
        }
        return null;
    }

    // Compact floor shape: total columns, gaps and the height spread the solver keyed off.
    private static string DescribeFloor(IReadOnlyList<FloorSegmentConfig> segments)
    {
        if (segments == null || segments.Count == 0) return "default 9-wide flat";

        int left = int.MaxValue, right = int.MinValue, covered = 0;
        float minTop = float.MaxValue, maxTop = float.MinValue;
        for (int s = 0; s < segments.Count; s++)
        {
            FloorSegmentConfig segment = segments[s];
            if (segment == null) continue;
            left = Mathf.Min(left, segment.LeftColumn);
            right = Mathf.Max(right, segment.LeftColumn + segment.ColumnCount - 1);
            covered += segment.ColumnCount;
            for (int i = 0; i < segment.ColumnCount; i++)
            {
                float top = segment.GetColumnHeightCells(i);
                minTop = Mathf.Min(minTop, top);
                maxTop = Mathf.Max(maxTop, top);
            }
        }
        if (covered == 0) return "default 9-wide flat";

        int span = right - left + 1;
        int gaps = Mathf.Max(0, span - covered);
        string shape = Mathf.Approximately(minTop, maxTop) ? "flat" : $"stepped {minTop:F0}-{maxTop:F0}";
        return $"{covered} cols, span {span}{(gaps > 0 ? $", {gaps} gap" : "")}, {shape}";
    }
}
