using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

/// <summary>
/// Editor-only difficulty report for puzzle (Height-Limit Waves) levels. Wave heights are
/// SOLVED, not authored, and deterministic per level - so the whole difficulty curve can be
/// inspected as a table instead of replayed. Runs the same <see cref="WaveSolver"/> the live
/// mode runs, over every ClearWaves/Endless level carrying a HeightLimitWavesModifier, and
/// writes PuzzleWaveReport.md at the repo root.
///
/// Use it to bracket difficulty: playtest ONE or TWO levels to calibrate
/// WaveSolver.CantileverColumnsPerStep (how many columns of supported width a row of rise
/// buys) and the rank density table, then read the table to confirm the other levels instead
/// of playing all sixteen. Read the "outward" column: cumulative block cells as a fraction of
/// what fits WITHIN the floor footprint at that line. Below 1.0 the wave can be solved without
/// ever building past the floor edges; above 1.0 the player is forced to cantilever outward,
/// and how far above 1.0 says how much of the wave lives out there. ("fill" is close to
/// tautological - the line is solved to hit the density - so it only reveals waves where the
/// one-cell minimum rise, not the math, set the height.)
/// </summary>
public static class PuzzleWaveReport
{
    private const string LevelsFolder = "Assets/Resources/Levels";
    private const string OutputPath = "PuzzleWaveReport.md";
    private const int ExtraWavesBeyondGoal = 3; // endless continues past the win - show the tail

    [MenuItem("Tools/MadTowers/Puzzle Wave Report")]
    public static void Generate()
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Puzzle Wave Report");
        sb.AppendLine();
        sb.AppendLine("Generated by `Tools/MadTowers/Puzzle Wave Report` (editor-only). Solved by the");
        sb.AppendLine("same `WaveSolver` the live mode uses, so these ARE the heights a run will see.");
        sb.AppendLine();
        sb.AppendLine($"Calibration: `CantileverColumnsPerStep = {WaveSolver.CantileverColumnsPerStep}` " +
                      $"column(s) of supported width per `{WaveSolver.CantileverRowsPerStep}` row(s) of rise, per side.");
        sb.AppendLine();
        sb.AppendLine("`fill` = block cells / buildable cells under the solved line (≈ the density by");
        sb.AppendLine("construction; a value BELOW it means the one-cell minimum rise set that line).");
        sb.AppendLine("`outward` = block cells / cells available inside the floor footprint only. Below 1.0 the");
        sb.AppendLine("wave fits over the floor; above 1.0 the player is forced to cantilever outward.");
        sb.AppendLine();

        string[] guids = AssetDatabase.FindAssets("t:LevelDefinition", new[] { LevelsFolder });
        var rows = new List<(string level, int rank, int wavesToWin, string floor, float avgCells, string table, float goalOutward, float goalLine, bool hasWin)>();

        var columnTops = new List<float>();
        var footprintTops = new List<float>();   // no cantilever: what fits over the floor alone
        var heights = new List<float>();

        foreach (string guid in guids)
        {
            string path = AssetDatabase.GUIDToAssetPath(guid);
            LevelDefinition level = AssetDatabase.LoadAssetAtPath<LevelDefinition>(path);
            if (level == null) continue;

            HeightLimitWavesModifier waves = FindWaveModifier(level);
            if (waves == null) continue;

            GameModeConfig config = level.GameModeConfig;
            IReadOnlyList<FloorSegmentConfig> segments = config != null ? config.FloorSegments : null;
            WaveSolver.BuildColumnTops(segments, columnTops);
            WaveSolver.BuildColumnTops(segments, footprintTops, includeCantilever: false);
            float avgCells = WaveSolver.AverageCellsPerPiece(
                config != null ? config.BlockBag : null, WaveSolver.MagmaRate(config));

            // Endless-paired wave levels have no win wave; show the same depth but never
            // label one, or the table invents a goal the level does not have.
            bool hasWin = level.TargetType == LevelTargetType.ClearWaves;
            int wavesToWin = hasWin ? Mathf.Max(1, Mathf.RoundToInt(level.TargetValue)) : 5;
            int shown = wavesToWin + ExtraWavesBeyondGoal;
            WaveSolver.SolveLineHeights(columnTops, avgCells, waves.DifficultyRank, shown, heights);

            var table = new StringBuilder();
            table.AppendLine("| wave | quota | cumulative | density | line (cells) | rise | capacity | fill | outward |");
            table.AppendLine("|---:|---:|---:|---:|---:|---:|---:|---:|---:|");
            float goalOutward = 0f;
            for (int n = 1; n <= shown; n++)
            {
                int cumulative = WaveSolver.CumulativeQuota(n);
                float line = heights[n - 1];
                float rise = n > 1 ? line - heights[n - 2] : line;
                float capacity = WaveSolver.CapacityAt(columnTops, line);
                float fill = capacity > 0f ? cumulative * avgCells / capacity : 0f;
                float footprint = WaveSolver.CapacityAt(footprintTops, line);
                float outward = footprint > 0f ? cumulative * avgCells / footprint : 0f;
                if (n == wavesToWin) goalOutward = outward;
                string marker = !hasWin ? " *(endless)*"
                    : n == wavesToWin ? " **(win)**" : (n > wavesToWin ? " *(endless)*" : "");
                table.AppendLine($"| {n}{marker} | {WaveSolver.QuotaForWave(n)} | {cumulative} | " +
                    $"{WaveSolver.DensityForWave(waves.DifficultyRank, n):F3} | {line:F1} | {rise:F1} | " +
                    $"{capacity:F0} | {fill:F2} | {outward:F2} |");
            }

            rows.Add((level.name, waves.DifficultyRank, wavesToWin, DescribeFloor(segments), avgCells,
                table.ToString(), goalOutward, heights[wavesToWin - 1], hasWin));
        }

        rows.Sort((a, b) => string.Compare(a.level, b.level, System.StringComparison.Ordinal));

        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine("| level | rank | waves to win | line at the win wave | outward at the win wave | floor |");
        sb.AppendLine("|---|---:|---:|---:|---:|---|");
        foreach (var row in rows)
        {
            sb.AppendLine($"| {row.level} | {row.rank} | {(row.hasWin ? row.wavesToWin.ToString() : "endless")} | {row.goalLine:F1} | {row.goalOutward:F2} | {row.floor} |");
        }
        sb.AppendLine();

        foreach (var row in rows)
        {
            sb.AppendLine($"## {row.level}");
            sb.AppendLine();
            sb.AppendLine($"rank {row.rank} · {(row.hasWin ? row.wavesToWin + " waves to win" : "endless (no win wave)")} · avg cells per counted block {row.avgCells:F2} · floor {row.floor}");
            sb.AppendLine();
            sb.Append(row.table);
            sb.AppendLine();
        }

        File.WriteAllText(OutputPath, sb.ToString());
        Debug.Log($"[PuzzleWaveReport] {rows.Count} puzzle level(s) written to {Path.GetFullPath(OutputPath)}");
    }

    private static HeightLimitWavesModifier FindWaveModifier(LevelDefinition level)
    {
        IReadOnlyList<LevelModifier> modifiers = level.Modifiers;
        if (modifiers == null) return null;
        for (int i = 0; i < modifiers.Count; i++)
        {
            if (modifiers[i] is HeightLimitWavesModifier waves) return waves;
        }
        return null;
    }

    // Compact floor shape: total columns, gaps and the height spread the solver keyed off.
    private static string DescribeFloor(IReadOnlyList<FloorSegmentConfig> segments)
    {
        if (segments == null || segments.Count == 0) return "default 9-wide flat";

        int left = int.MaxValue, right = int.MinValue, covered = 0;
        float minTop = float.MaxValue, maxTop = float.MinValue;
        for (int s = 0; s < segments.Count; s++)
        {
            FloorSegmentConfig segment = segments[s];
            if (segment == null) continue;
            left = Mathf.Min(left, segment.LeftColumn);
            right = Mathf.Max(right, segment.LeftColumn + segment.ColumnCount - 1);
            covered += segment.ColumnCount;
            for (int i = 0; i < segment.ColumnCount; i++)
            {
                float top = segment.GetColumnHeightCells(i);
                minTop = Mathf.Min(minTop, top);
                maxTop = Mathf.Max(maxTop, top);
            }
        }
        if (covered == 0) return "default 9-wide flat";

        int span = right - left + 1;
        int gaps = Mathf.Max(0, span - covered);
        string shape = Mathf.Approximately(minTop, maxTop) ? "flat" : $"stepped {minTop:F0}-{maxTop:F0}";
        return $"{covered} cols, span {span}{(gaps > 0 ? $", {gaps} gap" : "")}, {shape}";
    }
}
