using UnityEngine;
using UnityEngine.InputSystem;
using System.Collections.Generic;

// Per-spawn configuration: theme skin, block-variant data, collider forgiveness (I4),
// physics material fallback, and per-level GameModeConfig application.
public partial class BlockController
{

    // One sprite covers the whole tetromino (piece_T.png etc.), so every piece of a shape
    // looks identical. Cell renderers are hidden; their colliders (the entire physics
    // footprint) are untouched, and the skin child has no collider, so BlockCellGeometry
    // and all casts never see it. Sprites are generated by Tools/generate_piece_sprites.py.
    private void ApplyBlockSkin()
    {
        string shape = ThemeSkins.ExtractShapeToken(name);
        if (string.IsNullOrEmpty(shape)) return;

        Sprite pieceSprite = ThemeSkins.LoadPiece(shape);
        if (pieceSprite == null)
        {
            Debug.LogWarning(
                $"[BlockSkin] No sprite at Resources/{ThemeSkins.Folder}/piece_{shape} " +
                $"for '{name}' - piece renders as plain cells. Check the Skins folder imported correctly.",
                this);
            return;
        }

        SpriteRenderer[] cellRenderers = GetComponentsInChildren<SpriteRenderer>();
        if (cellRenderers.Length == 0) return;

        Vector2 min = cellRenderers[0].transform.localPosition;
        Vector2 max = min;
        foreach (var sr in cellRenderers)
        {
            Vector2 p = sr.transform.localPosition;
            min = Vector2.Min(min, p);
            max = Vector2.Max(max, p);
            sr.enabled = false;
        }

        GameObject skinGo = new GameObject("PieceSkin");
        skinGo.transform.SetParent(transform, false);
        skinGo.transform.localPosition = new Vector3((min.x + max.x) * 0.5f, (min.y + max.y) * 0.5f, 0f);

        SpriteRenderer skinRenderer = skinGo.AddComponent<SpriteRenderer>();
        skinRenderer.sprite = pieceSprite;
        skinRenderer.sortingLayerID = cellRenderers[0].sortingLayerID;
        skinRenderer.sortingOrder = cellRenderers[0].sortingOrder;
    }

    public void ApplyData(BlockData data)
    {
        if (data == null) return;

        _appliedData = data;
        if (_rb == null) _rb = GetComponent<Rigidbody2D>();
        _rb.mass = data.Mass;
        _rb.sharedMaterial = ResolveBlockMaterial(data.PhysicsMaterial);
        _gravityScaleMultiplier = data.GravityScaleMultiplier;

        SpriteRenderer[] renderers = GetComponentsInChildren<SpriteRenderer>();
        foreach (var sr in renderers)
        {
            sr.color = data.ColorTint;
            if (data.SpriteOverride != null) sr.sprite = data.SpriteOverride;
            if (data.MaterialOverride != null) sr.sharedMaterial = data.MaterialOverride;
        }

        ResetControlTargets();
        data.OnApplied(this);
    }

    // Physics shapes are slightly smaller than the visual cells (Tricky-Towers style). With an
    // exactly cell-sized footprint a piece can never enter a gap that is exactly its own size:
    // any sub-pixel drift of a neighbour pinches the slot, the piece wedges on the corners, and
    // the depenetration shoves the walls apart. The sprite stays full size; only collision
    // shrinks. The inset is uniform so it survives 90-degree rotations, and
    // BoxCollider2D.edgeRadius expands outward, so the box is shrunk by 2r on top of the inset.
    private void ApplyColliderForgiveness()
    {
        BoxCollider2D[] colliders = GetComponentsInChildren<BoxCollider2D>();
        if (colliders.Length == 0) return;

        float footprintScale = Mathf.Clamp(colliderFootprintScale, 0.85f, 1f);
        for (int i = 0; i < colliders.Length; i++)
        {
            BoxCollider2D box = colliders[i];
            Vector2 targetSize = box.size * footprintScale;
            float requestedRadius = Mathf.Max(0f, colliderCornerRadiusFraction) * gridSpacing;
            float radius = Mathf.Min(requestedRadius, Mathf.Min(targetSize.x, targetSize.y) * 0.45f);
            box.size = new Vector2(
                Mathf.Max(0.05f, targetSize.x - 2f * radius),
                Mathf.Max(0.05f, targetSize.y - 2f * radius));
            box.edgeRadius = radius;
        }
    }

    // Returns the variant's own PhysicsMaterial2D if one is assigned; otherwise a single
    // shared fallback material so blocks always have real friction (a null material would
    // leave them on engine defaults and make tall towers slide apart).
    private PhysicsMaterial2D ResolveBlockMaterial(PhysicsMaterial2D explicitMaterial)
    {
        if (explicitMaterial != null) return explicitMaterial;

        if (_sharedFallbackMaterial == null)
        {
            _sharedFallbackBaseFriction = Mathf.Max(0f, defaultBlockFriction);
            _sharedFallbackMaterial = new PhysicsMaterial2D("BlockFallbackMaterial")
            {
                friction = ResolveStandardBlockFriction(),
                bounciness = defaultBlockBounciness
            };
        }

        return _sharedFallbackMaterial;
    }

    private static void RefreshStandardBlockFriction()
    {
        if (_sharedFallbackMaterial == null) return;

        _sharedFallbackMaterial.friction = ResolveStandardBlockFriction();
    }

    private static float ResolveStandardBlockFriction()
    {
        return Mathf.Max(0f, _sharedFallbackBaseFriction * _standardBlockFrictionMultiplier);
    }

    public void ApplyConfig(GameModeConfig config)
    {
        if (config == null) return;

        gridSpacing = config.GridSpacing;
        horizontalPlacementBufferColumns = config.HorizontalPlacementBufferColumns;

        groundedCheckDistance = config.GroundedCheckDistance;
        maxLandingImpactSpeed = config.MaxLandingImpactSpeed;
        settleLinearThreshold = config.SettleLinearThreshold;
        settleAngularThreshold = config.SettleAngularThreshold;
        settleTime = config.SettleTime;
        sleepSettledBlocksOnLock = config.SleepSettledBlocksOnLock;
        microAlignSettledBlocks = config.MicroAlignSettledBlocks;
        microAlignMaxColumnFraction = config.MicroAlignMaxColumnFraction;
        microAlignMaxRotationDegrees = config.MicroAlignMaxRotationDegrees;
        maxControlTime = config.MaxControlTime;

        _floorSegments = config.FloorSegments;
        ResetControlTargets();
    }

}
